name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-musl, exe: amd64-linux, os: ubuntu-latest, test: true }
          - { target: aarch64-unknown-linux-musl, exe: aarch64-linux, os: ubuntu-latest, test: true }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest, test: true }
          - { target: aarch64-apple-darwin, exe: macos, os: macos-latest, test: false } # run aarch64 binary is not supported
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.job.target }}
          components: rust-src # necessary for wasi, because there isn't a cross image for it
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --verbose --target=${{ matrix.job.target }} --locked
          command: build
      if: ${{ matrix.job.test }} == true
        - uses: actions-rs/cargo@v1
          with:
            use-cross: true
            args: --verbose --target=${{ matrix.job.target }} --locked
            command: test
