name: CI

on: [push, pull_request]

jobs:     
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target --verbose ${{ matrix.target }}
          use-cross: false
        
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target --verbose ${{ matrix.target }}
          use-cross: false
        
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target --verbose ${{ matrix.target }}
          use-cross: false
        
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target --verbose ${{ matrix.target }}
          use-cross: false
