name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-musl, exe: amd64-linux, os: ubuntu-latest }
          - { target: aarch64-unknown-linux-musl, exe: aarch64-linux, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
          - { target: aarch64-apple-darwin, exe: macos, os: macos-latest }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.job.target }}
          components: rust-src # necessary for wasi, because there isn't a cross image for it
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --verbose --target=${{ matrix.job.target }} --locked
          command: build
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --verbose --target=${{ matrix.job.target }} --locked
          command: test



  # macos:
  #   runs-on: macos-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       channel: [stable]
  #       target:
  #         - x86_64-apple-darwin
  #         - aarch64-apple-darwin

  #   steps:
  #     - name: Setup | Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup | Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true
  #         profile: minimal
  #         target: ${{ matrix.target }}
  #     - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
  #     - name: Build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --verbose --target ${{ matrix.target }}
  #         use-cross: false
        
  #     - name: Test
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: --verbose --target ${{ matrix.target }}
  #         use-cross: false
        
  # linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       channel: [stable]
  #       target:
  #         - x86_64-unknown-linux-gnu
  #         - aarch64-unknown-linux-gnu

  #   steps:
  #     - name: Setup | Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup | Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true
  #         profile: minimal
  #         target: ${{ matrix.target }}
  #     - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
  #     - name: Build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --verbose --target ${{ matrix.target }}
  #         use-cross: false
        
  #     - name: Test
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: --verbose --target ${{ matrix.target }}
  #         use-cross: false
